### ISSUE TITLE
Set scatter circle radius with a getter?

### ISSUE THREAD

**Issue by basilesimon** [Matthew-Weber/ReutersCharter#2]
Currently the spec for setting the radius of `<circle/>` in the scatter template is:

- `hardRadius: 10`, 
- OR `rValue: "columnName"`,
- both being modifiable by `radiusModifier: int`

I wonder if we could condense this into one expression, maybe with a getter function?

**Comment by Matthew-Weber** [comment]
Or possibly as an object?  might be able to more explicitly label the optioning?

```
	rValue:{
		column:"columnName", //can set as "none"
		multiplier:int
	},
```

**Comment by basilesimon** [comment]
so... something like this?

```js
rValue:{
    data: "columnName", // a column in your data OR an integer
    multiplier:int
},
```

**Comment by basilesimon** [comment]
Hey @Matthew-Weber, curious to know your thoughts on this :)

**Comment by Matthew-Weber** [comment]
I'm into it.  It's on my list.

**Comment by Matthew-Weber** [comment]
This change is live.
